[project]
name = "complex-prediction"
version = "0.1.0"
description = "A snakemake pipeline to predict protein complexes"
authors = ["Sibbe Bakker <sibbe.l.bakker@gmail.com>"]
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64"]

[tasks]
download_submodules = "git submodule init; git submodule update"
update_submodules = {cmd = "git submodule update --remote --merge", depends_on = ['download_submodules']}
start = {cmd = "snakemake --use-conda", depends_on = ["update_submodules"]}
t = "tree results -L 5"
help  = "snakemake help -c 1 --quiet all"
make = "snakemake --use-conda -c 1"
update_dag = "snakemake --quiet all -c 1 'results/method.png' && mv results/method.png resources; mv resources/method.png resources/pipeline.png"


[dependencies]
colabfold = ">=1.5.5,<1.6"
snakemake = ">=7.32.4,<7.33"
conda = ">=24.4.0,<24.5"
pip = ">=24.0,<25"
immutabledict = ">=4.2.0,<4.3"
tree = ">=2.1.1,<2.2"
graphviz = ">=9.0.0,<9.1"

[pypi-dependencies]
jax = { version = "*", extras = ["cuda12-pip"] }

[system-requirements]
linux="4.18"
