[project]
name = "complex-prediction"
version = "0.1.0"
description = "A snakemake pipeline to predict protein complexes"
authors = ["Sibbe Bakker <sibbe.l.bakker@gmail.com>"]
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64"]

[tasks]
download_submodules = "git submodule init; git submodule update"
update_submodules = {cmd = "git submodule update --remote --merge", depends_on = ['download_submodules']}
start = {cmd = "snakemake --use-conda", depends_on = ["update_submodules"]}
make = "snakemake --use-conda -c 1"

[dependencies]
curl = ">=8.7.1,<8.8"
snakemake = ">=8.10.8,<8.11"
conda = ">=24.3.0,<24.4"
tree = ">=2.1.1,<2.2"
mamba = ">=1.5.8,<1.6"
wget = ">=1.21.4,<1.22"
findutils = ">=4.6.0,<4.7"
python = ">=3.12.3,<3.13"
biopython = ">=1.83,<2"
jupyter = ">=1.0.0,<1.1"
gzip = ">=1.13,<2"


# Run the pipeline on old linux
[system-requirements]
linux="4.18"

