[project]
name = "complex-prediction"
version = "0.1.0"
description = "A snakemake pipeline to predict protein complexes"
authors = ["Sibbe Bakker <sibbe.l.bakker@gmail.com>"]
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64"]

[tasks]
make = "snakemake --use-conda -c 1"
test = "snakemake --use-conda -c 1 -np"
slurm = "snakemake --use-conda --workflow-profile workflow/profiles/slurm"
help  = "bash workflow/help.sh"
make-help  = "sed -n 's/^##//p' workflow/Snakefile"
make-dag = "mkdir resources; snakemake --quiet all -c 1 'results/method.png' && mv results/method.png resources; mv resources/method.png resources/pipeline.png"
make-ascii = "mkdir resources; pixi run make results/method-simple.ascii &&  mv results/method-simple.ascii resources/pipeline.ascii; cat resources/pipeline.ascii"


[dependencies]
conda = ">=24.4.0,<24.5"
snakemake = ">=8.10.8,<8.11"
pip = ">=24.0,<25"
tree = ">=2.1.1,<2.2"
snakemake-executor-plugin-slurm = ">=0.6.0,<0.7"
mamba = ">=1.5.8,<1.6"

[pypi-dependencies]
jax = { version = "*", extras = ["cuda12-pip"] }

[system-requirements]
linux="4.12.14"
