executor: slurm
latency-wait: 60
jobname: "complex-prediction-{rule}.{jobid}" 
jobs: 100

default-resources:
  - mem_mb=2000
  - runtime='1440'
  - disk_mb=5000
  - constraint="cpu"
  - slurm_partition='cpu1'
  - slurm_account="mpmp_cpu"
set-resources:
  colabfold:
    mem_mb: 32000
    slurm_extra:  "'--gres=gpu:a100:1'"
    constraint: "gpu"
    cpus_per_task: 10
    slurm_partition: 'gpu1'
    runtime: 40
    slurm_account: "mpmp_gpu"
  combfold:
    runtime: 200 # 24 hour
    cpus_per_task: 45
    mem_per_cpu: 1800
